# 21.异常处理

异常处理允许程序员处理程序中可能出现的意外情况。比如 java.io 包中的`FileReader`类用来打开一个文件。创建该类的一个实例将会导致 IDE 给出一个提示，提示该类的构造函数可能会抛出一个`FileNotFoundException`。试图运行程序也会导致编译器指出这一点。

```
import java.io.*;
public class MyClass
{
  public static void main(String[] args)
  {
    // Compile-time error
    FileReader file = new FileReader("missing.txt");
  }
}

```

## 试着接住

为了处理这个编译时错误，必须使用一个`try-catch`语句来捕获异常。该语句由一个包含可能导致异常的代码的`try`块和一个或多个`catch`子句组成。如果`try`块成功执行，程序将在`try-catch`语句后继续运行，但如果出现异常，执行将传递给第一个能够处理该异常类型的`catch`块。

```
try {

  FileReader file = new FileReader("missing.txt");
}
catch(FileNotFoundException e) {}

```

## 捕捉块

在前面的例子中，`catch`块仅被设置为处理`FileNotFoundException`。如果`try`块中的代码可以抛出更多种类的异常，并且所有的异常都应该以同样的方式处理，那么可以捕捉更一般的异常，比如所有异常都源自的`Exception`类本身。这个`catch`子句将能够处理从这个类继承的所有异常，包括`FileNotFoundException`。请记住，一个更一般的异常需要在一个更具体的异常之后被捕获。子句必须总是定义一个异常对象。这个对象可以用来获得关于异常的更多信息，比如使用`getMessage`方法对异常的描述。

```
catch(FileNotFoundException e) {
  System.out.print(e.getMessage());
}
catch(Exception e) {
  System.out.print(e.getMessage());
}

```

从 Java 7 开始，可以使用单个`catch`块捕获不同类型的多个异常。这有助于避免代码重复，在以相同方式处理多个异常的情况下，不必捕获过于一般化的异常类型。在`catch`子句中，每个异常用竖线(`|`)分隔。

```
catch(IOException | SQLException e) {
  // Handle exception
}

```

## 最终阻止

作为`try-catch`语句的最后一个子句，可以添加一个`finally`块。这个块用于清理分配在`try`块中的资源，并且无论是否有异常都会执行。在本例中，在`try`块中打开的文件应该被关闭，但前提是它被成功打开。为了能够从`finally`子句访问`FileReader`对象，它必须在`try`块之外声明。此外，因为`close`方法也可以抛出异常，所以该方法需要用另一个`try-catch`块包围。请记住，如果您忘记关闭一个资源对象，Java 的垃圾收集器最终会为您关闭该资源，但是自己关闭它是一个很好的编程实践。

```
FileReader file = null;
try {
  file = new FileReader("missing.txt");
}
catch(FileNotFoundException e) {
  System.out.print(e.getMessage());
}
finally {
  if (file != null) {
    try { file.close(); }
    catch(IOException e) {}
  }
}

```

Java 7 增加了资源尝试特性。该特性允许通过在`try`关键字后的括号中定义资源对象来自动关闭资源对象。为此，资源必须实现`java.lang.AutoClosable`接口。这个接口仅由`close`方法组成，该方法在隐式的`finally`语句中被自动调用。因此，前面的例子可以简化如下:

```
try(FileReader file = new FileReader("missing.txt")) {
  // Read file
}
catch(FileNotFoundException e) {
  // Handle exception
}

```

对于自动关闭，可以包括多个资源对象，用分号分隔。为了提高可读性，Java 9 使得在括号外声明的对象可以被 try-with-resources 语句引用，只要这些资源是最终的或者实际上是最终的。

```
// Final resource
final FileReader file1 = new FileReader("file1.txt");

// Effectively final resource (never changed)
FileReader file2 = new FileReader("file2.txt");

try(file1; file2) {
  // Read files
}
catch(FileNotFoundException e) {
  // Handle exception
}

```

## 抛出异常

当某个方法无法恢复的情况发生时，它可以生成自己的异常，通知调用者该方法已经失败。它使用`throw`关键字，后跟一个`Throwable`类型的新实例。

```
static void makeException()
{
  throw new Throwable("My Throwable");
}

```

## 已检查和未检查的异常

Java 中的异常分为两类——检查的和未检查的——这取决于它们是否需要被指定。抛出检查异常的方法(例如，`IOException`)将不会编译，除非在方法的参数列表后使用`throws`子句指定它，并且调用方法捕获异常。另一方面，未检查的异常，如`ArithmeticException`，不必被捕获或指定。请注意，要指定多个异常，异常类型由逗号分隔。

```
static void MakeException()
throws IOException, FileNotFoundException
{
  // ...
  throw new IOException("My IO exception");
  // ...
  throw new FileNotFoundException("File missing");
}

```

## 异常层次结构

像 Java 中的大多数其他东西一样，异常是存在于层次结构中的类。这个层次结构的根(在`Object`下面)是`Throwable`类，这个类的所有后代都可以被抛出和捕获。从`Throwable`继承而来的是`Error`和`Exception`类。从`Error`开始下降的类用于指示不可恢复的异常，例如`OutOfMemoryError`。这些是未检查的，因为一旦它们发生，即使它们被发现，程序员也不可能对它们做任何事情。

从`Exception`往下是`RuntimeExceptions`，也是未勾选的。这些异常几乎在任何代码中都可能发生，因此捕捉和指定它们会很麻烦。例如，被零除会抛出一个`ArithmeticException`，但是用一个`try-catch`包围每个除法运算会很麻烦。还有一些与检查异常相关的开销，检查这些异常的成本通常超过捕获它们的好处。其他的`Exception`后代，那些不继承`RuntimeExceptions`的，都被查了。这些是可以从中恢复的异常，并且必须被捕获和指定。